version: '3.9'
services:
  oauth:
    build: .
    image: agarwood/oauth:${AGARWOOD_VERSION}
    command: ['php', '/var/www/agarwood/bin/agarwood', 'http:start']
    container_name: agarwood-oauth
    environment:
      - TIMEZONE=Asia/Shanghai
    restart: always
    env_file:
      - .env
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
      - ${RPC_SERVER_PORT}:${RPC_SERVER_PORT}
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql
  redis:
    image: "redis:6.2-alpine"
    container_name: redis
    restart: always
    ports:
      - "16379:6379"
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    restart: always
    volumes:
      - /usr/local/mysql/data:/var/lib/mysql
      - /private/etc/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MASTER_DB_PWD}
